[package]
name = "tron-state"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tron-types.workspace = true
tron-storage.workspace = true
tron-proto.workspace = true
thiserror.workspace = true
prost.workspace = true
tron-chain.workspace = true
