[package]
name = "tron-actuators"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tron-types.workspace = true
tron-proto.workspace = true
tron-state.workspace = true
tron-consensus.workspace = true
tron-vm.workspace = true
tron-storage.workspace = true
thiserror.workspace = true
prost.workspace = true
prost-types.workspace = true
hex.workspace = true
primitive-types.workspace = true
