[package]
name = "tron-consensus"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tron-types.workspace = true
tron-proto.workspace = true
tron-chain.workspace = true
tron-crypto.workspace = true
prost.workspace = true
thiserror.workspace = true
hex.workspace = true
