[package]
name = "tron-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
description = "Rust codegen of the Tron protobuf/gRPC schema (vendored from java-tron)."

[dependencies]
prost.workspace = true
prost-types.workspace = true
tonic.workspace = true

[build-dependencies]
tonic-build.workspace = true
